### ISSUE TITLE
Try to open an url in browser

### ISSUE THREAD

**Issue by Millares** [jarun/ddgr#67] opened 2018-09-11 02:55 UTC
I set the environment var BROWSER, ans when try to open an url using the index number ddgr blows.

![2018-09-10_1536634829](https://user-images.githubusercontent.com/17129644/45335282-9c58b000-b54c-11e8-9816-a6884b48d50f.png)

**Comment by jarun** [comment] 2018-09-11 05:00
You are on python 3.7 and this is a duplicate of issue #63.

**Closed by jarun** 2018-09-11 05:00 UTC

**Comment by christophergeiger3** [comment] 2018-10-07 03:16
I'm also having this issue, I have the `BROWSER` var set to `opera`, and I'm running python 3.7. For some reason running `ddgr --url-handler=opera` has the expected functionality though.
