### ISSUE TITLE
Wrong version number reported by code (again)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [jarun/ddgr#155] opened 2023-04-22 23:16 UTC
Cf. #110.

```
[git pull . .]
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 18 (delta 8), reused 16 (delta 6), pack-reused 0
Unpacking objects: 100% (18/18), 31.44 KiB | 2.62 MiB/s, done.
   1301ec7..c40de97  main       -> origin/main
 * [new tag]         v2.1       -> v2.1
$ sudo make install
install -m755 -d /usr/local/bin
install -m755 -d /usr/local/share/man/man1
install -m755 -d /usr/local/share/doc/ddgr
gzip -c ddgr.1 > ddgr.1.gz
install -m755 ddgr /usr/local/bin
install -m644 ddgr.1.gz /usr/local/share/man/man1
install -m644 README.md /usr/local/share/doc/ddgr
rm -f ddgr.1.gz
$ ddgr --version
1.9
```

But perhaps I do something wrong. (The output above was generated today, via git - or, more precisely, via a script that I have for installing code via git.)

**Comment by jarun** [comment] 2023-09-10 04:15
Sorry, I can't reproduce this locally. it seems like you have an older version of `ddgr` installed in a different location.

Try `which ddgr`.

Here's what I have:

```
$ sudo make uninstall
rm -f /usr/local/bin/ddgr
rm -f /usr/local/share/man/man1/ddgr.1.gz
rm -rf /usr/local/share/doc/ddgr
$ git pull --rebase
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), 7.12 KiB | 2.37 MiB/s, done.
From https://github.com/jarun/ddgr
   2546786..b3838c9  main       -> origin/main
Updating 2546786..b3838c9
Fast-forward
 README.md | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
$ sudo make install
install -m755 -d /usr/local/bin
install -m755 -d /usr/local/share/man/man1
install -m755 -d /usr/local/share/doc/ddgr
gzip -c ddgr.1 > ddgr.1.gz
install -m755 ddgr /usr/local/bin
install -m644 ddgr.1.gz /usr/local/share/man/man1
install -m644 README.md /usr/local/share/doc/ddgr
rm -f ddgr.1.gz
$ ddgr --version
2.1
$ which ddgr
/usr/local/bin/ddgr
```

Closing as this appears to be a local issue.

**Closed by jarun** 2023-09-10 04:15 UTC
