### ISSUE TITLE
Opera browser not launching

### ISSUE THREAD

**Issue by christophergeiger3** [jarun/ddgr#69] opened 2018-10-07 03:20 UTC
_Originally posted by @christophergeiger3 in https://github.com/jarun/ddgr/issue_comments#issuecomment-427622473_

Running `O index` throws a `register() takes from 2 to 3 posistional arguments but 4 were given` error.
Runnning `ddgr --url-handler=opera` has the expected functionality though.
My `BROWSER` var is set to `/usr/bin/opera`
![image](https://user-images.githubusercontent.com/20095580/46577902-637ef000-c9bf-11e8-9d14-23410f2042b1.png)

**Comment by jarun** [comment] 2018-10-07 07:03
There are 2 problems:

1. Python 3.7 issue is a duplicate of #63.

2. Opera doesn't play well with webbrowser.open(). This is discussed here: https://stackoverflow.com/questions/51123537/webbrowser-open-breaks-the-link-python-3-7

--url-handler=opera uses the other method.

**Comment by jarun** [comment] 2018-10-07 07:03
I'll test and document the opera issue.

**Closed by jarun** 2018-10-07 07:03 UTC
